version: '3.0'

networks:
  classting-nw:

services:
  classting-app:
    image: classting-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - classting-db
    networks:
      - classting-nw

  classting-db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: classting-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: classting
      MYSQL_DATABASE: classting
      MYSQL_USER: classting
      MYSQL_PASSWORD: classting
    ports:
      - "3306:3306"
    networks:
      - classting-nw
    volumes:
      - ./source/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./source/my.cnf:/etc/mysql/conf.d/my.cnf