definitions:
  domain.CreateSchoolRequest:
    properties:
      name:
        example: 클래스팅
        type: string
      region:
        example: 서울
        type: string
    required:
    - name
    - region
    type: object
  domain.CreateUserRequest:
    properties:
      password:
        example: "1234"
        type: string
      userName:
        example: classting_admin
        type: string
      userType:
        allOf:
        - $ref: '#/definitions/domain.UserType'
        example: ADMIN
    required:
    - password
    - userName
    - userType
    type: object
  domain.ListSchoolsResponse:
    properties:
      cursor:
        type: integer
      schools:
        items:
          $ref: '#/definitions/domain.SchoolDTO'
        type: array
    type: object
  domain.LoginUserRequest:
    properties:
      password:
        example: "1234"
        type: string
      userName:
        example: classting_admin
        type: string
    required:
    - password
    - userName
    type: object
  domain.LoginUserResponse:
    properties:
      accessToken:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDg4ODgxOTIsInVzZXJJRCI6MX0.WVQGpeNbCpWSKuvYO7rFv6HoXaEA4_VQZSl7oMhmROk
        type: string
      expiresIn:
        example: 1708888192
        type: integer
    required:
    - accessToken
    - expiresIn
    type: object
  domain.SchoolDTO:
    properties:
      id:
        type: integer
      name:
        type: string
      region:
        type: string
    type: object
  domain.UserType:
    enum:
    - ADMIN
    - STUDENT
    type: string
    x-enum-varnames:
    - UserUseTypeAdmin
    - UserUseTypeStudent
info:
  contact: {}
paths:
  /schools:
    get:
      description: '학교 목록을 조회합니다 (권한: 관리자, 학생) userID를 쿼리스트링에 입력시 해당 유저의 학교 목록을 조회합니다.
        디폴트 20개씩 조회'
      parameters:
      - description: 커서
        in: query
        name: cursor
        type: integer
      - description: 유저 아이디
        in: query
        name: userID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 학교 목록
          schema:
            $ref: '#/definitions/domain.ListSchoolsResponse'
      security:
      - BearerAuth: []
      summary: 학교 목록 조회 [테스트 추가 API]
      tags:
      - Schools
    post:
      consumes:
      - application/json
      description: 지역, 학교명으로 학교를 생성합니다. (지역, 학교명이 중복되지 않아야 합니다.)
      parameters:
      - description: 학교 생성 요청
        in: body
        name: CreateSchoolRequest
        required: true
        schema:
          $ref: '#/definitions/domain.CreateSchoolRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: 학교 생성 [필수 구현]
      tags:
      - Schools
  /users:
    post:
      consumes:
      - application/json
      description: 관리자, 학생의 역할로 회원가입 요청 (관리자의 경우 Type = ADMIN, 학생의 경우 Type = STUDENT)
      parameters:
      - description: 회원가입 요청
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUserRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: 회원가입 [테스트 추가 API]
      tags:
      - User
  /users/login:
    post:
      consumes:
      - application/json
      description: '예시 유저네임: classting_admin, 비밀번호: classting, Type = ADMIN / classting_student,
        비밀번호: classting, Type = STUDENT'
      parameters:
      - description: 로그인 요청
        in: body
        name: LoginUserRequest
        required: true
        schema:
          $ref: '#/definitions/domain.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.LoginUserResponse'
      summary: 로그인 [테스트 추가 API]
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
