CREATE TABLE users
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    user_name   VARCHAR(255) UNIQUE NOT NULL,
    password    VARCHAR(255)        NOT NULL,
    user_type   ENUM ('ADMIN', 'STUDENT') DEFAULT 'STUDENT',
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delete_date TIMESTAMP NULL
);

